defaults: &defaults
  clientId: <insert clientId>
  secret: <insert secret>
  callback: http://youruniquedomain.com:3000/callback


#only modify these if you need to override default behaviour based on env!
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults